### ISSUE TITLE
onReceiveGroupMessage调用引发异常

### ISSUE THREAD

**Issue by SPCS233** [Zaitonn/Serein#13]
用
![Screenshot_20220730_123311_mark via](https://user-images.githubusercontent.com/79357769/181872482-3cf6a890-c534-4bf2-89fb-48472c64bb3d.jpg)
![Screenshot_20220730_122816_com microsoft rdc androidx](https://user-images.githubusercontent.com/79357769/181872486-f5fa5eeb-4333-4d96-8ded-292e44218f00.jpg)
然后就报错了

**Comment by SPCS233** [comment]
自己写跟别的也一样

**Comment by Zaitonn** [comment]
![IMG_8893(20220730-160400)](https://user-images.githubusercontent.com/103164490/181888317-f69f7408-a261-4f00-8a98-211550477757.JPG)

玄学bug，前面触发过一次后面又正常了

**Comment by Zaitonn** [comment]
目测大概是网络不好然后访问API超时然后引发Exception了

**Comment by SPCS233** [comment]
还有一些小问题
我点击按钮关服
启动时说，检测到服务器在运行
点重启按钮，有时候会直接关服，不重启

**Comment by SPCS233** [comment]
![53577b78bd71881](https://user-images.githubusercontent.com/79357769/181899855-ed5c6ee4-455e-4aef-b17e-5d2cd55dd3d4.png)
![76108ee52e461489](https://user-images.githubusercontent.com/79357769/181899872-0bbf2aab-d2b4-4bd2-becd-45423ae4de06.png)
还有绑定的问题
正则，我现在没有问题
旧版本不会重复
现在新版重复了

**Comment by SPCS233** [comment]
> ![53577b78bd71881](https://user-images.githubusercontent.com/79357769/181899855-ed5c6ee4-455e-4aef-b17e-5d2cd55dd3d4.png) ![76108ee52e461489](https://user-images.githubusercontent.com/79357769/181899872-0bbf2aab-d2b4-4bd2-becd-45423ae4de06.png) 还有绑定的问题 正则，我现在没有问题 旧版本不会重复 现在新版重复了

是从旧版替换到新版

**Comment by SPCS233** [comment]
> 目测大概是网络不好，访问API超时就报错了

刚刚试了一下，还是一样报错

**Comment by SPCS233** [comment]
16:35:23 [JSFunc:Tigger()] onReceivePacket
16:35:25 [JSFunc:Tigger()] onReceivePacket
16:35:30 [JSFunc:Tigger()] onReceivePacket
16:35:30 [JSFunc:Tigger()] onReceiveGroupMessage
16:35:30 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ReferenceError: group is not defined
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Serein.Plugin.JSFunc.<>c__DisplayClass2_0.<Trigger>b__7(Delegate x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Serein.Plugin.JSFunc.Trigger(String EventName, Object[] Args)
16:35:30 [JSFunc:Tigger()] onReceivePacket
16:35:31 [JSFunc:Tigger()] onReceiveGroupMessage
16:35:31 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ReferenceError: group is not defined
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Serein.Plugin.JSFunc.<>c__DisplayClass2_0.<Trigger>b__7(Delegate x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Serein.Plugin.JSFunc.Trigger(String EventName, Object[] Args)
16:35:31 [JSFunc:Tigger()] onReceivePacket
16:35:31 [JSFunc:Tigger()] onReceiveGroupMessage
16:35:31 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ReferenceError: group is not defined
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Serein.Plugin.JSFunc.<>c__DisplayClass2_0.<Trigger>b__7(Delegate x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Serein.Plugin.JSFunc.Trigger(String EventName, Object[] Args)
16:35:31 [JSFunc:Tigger()] onReceivePacket
16:35:32 [JSFunc:Tigger()] onReceiveGroupMessage
16:35:32 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ReferenceError: group is not defined
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Serein.Plugin.JSFunc.<>c__DisplayClass2_0.<Trigger>b__7(Delegate x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Serein.Plugin.JSFunc.Trigger(String EventName, Object[] Args)
16:35:32 [JSFunc:Tigger()] onReceivePacket
16:35:33 [JSFunc:Tigger()] onReceiveGroupMessage
16:35:33 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ReferenceError: group is not defined
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Serein.Plugin.JSFunc.<>c__DisplayClass2_0.<Trigger>b__7(Delegate x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Serein.Plugin.JSFunc.Trigger(String EventName, Object[] Args)
16:35:33 [JSFunc:Tigger()] onReceivePacket

**Comment by Zaitonn** [comment]
> > 目测大概是网络不好，访问API超时就报错了
> 
> 刚刚试了一下，还是一样报错

你试一下浏览器能不能打开 https://v1.hitokoto.cn

**Comment by Zaitonn** [comment]
麻烦发一下你的那个插件
感觉是`group`参数写错了

**Comment by SPCS233** [comment]
> > > 目测大概是网络不好，访问API超时就报错了
> > 
> > 
> > 刚刚试了一下，还是一样报错
> 
> 你试一下浏览器能不能打开 https://v1.hitokoto.cn

可以

**Comment by SPCS233** [comment]
serein.registerPlugin("测试","v1.0","Chlna6666","不知道是干啥的");

serein.setListener("onReceiveGroupMessage",GroupMessage)
function GroupMessage(group,user,msg,shownname){
    if(msg == "一言"){
        serein.sendGroup(group,JSON.parse(serein.createRequest("https://v1.hitokoto.cn")).hitokoto); 
    }
}``

**Comment by SPCS233** [comment]
![60485ef6c469362b](https://user-images.githubusercontent.com/79357769/181904901-9c547922-c007-422b-94a0-670bb7bb6fbc.png)
![53577b78bd71881](https://user-images.githubusercontent.com/79357769/181904903-923f0e38-daec-4307-9890-bb69a12d1979.png)
![76108ee52e461489](https://user-images.githubusercontent.com/79357769/181904905-0abda63c-33e6-4731-9e43-d1870579a23f.png)
还有重复问题
我也不知道为什么
新版才有的问题
更新方式替换文件

**Comment by Zaitonn** [comment]
插件有重复吗

**Comment by SPCS233** [comment]
> 插件和正则有重复吗

绝对没有
插件只是上手试一试
正则以前用的好好的
就新版本有问题

**Comment by Zaitonn** [comment]
麻烦你把整个serein的文件夹打包一份发我
死活复现不了这些bug（悲）

**Comment by SPCS233** [comment]
我觉得主要问题可能是
重载插件的问题
无法重载
有可能是因为这个问题导致的

**Comment by SPCS233** [comment]
> 我觉得主要问题可能是 重载插件的问题 无法重载 有可能是因为这个问题导致的
大概是
我换了文字
重载没有用
还是旧的

**Comment by SPCS233** [comment]
> 麻烦你把整个serein的文件夹打包一份发我 死活复现不了这些bug（悲）

QQ聊

**Comment by SPCS233** [comment]
机器人说话重复重启可以解决
估计是启动了两个
主要原因可能是因为https://github.com/Zaitonn/Serein/issues/14
导致的有两个机器人

**Comment by SPCS233** [comment]
> 机器人说话重复重启可以解决 估计是启动了两个 主要原因可能是因为#14 导致的有两个机器人

这个原因也导致插件无法重载
所以最终原因
https://github.com/Zaitonn/Serein/issues/14
应该是

**Comment by Zaitonn** [comment]
理论上即使多开也不会影响关服……怪了

**Comment by SPCS233** [comment]
> 理论上即使多开也不会影响关服……怪了

前一个版本都没事

**Comment by Zaitonn** [comment]
能给个关服失败的详细步骤吗
得复现这个方法才行

**Comment by SPCS233** [comment]
> 能给个关服失败的详细步骤吗 得复现这个方法才行

Q：2700758832
